export const mfData = {
  reqId: '692516470-090449085',
  pan: 'EVKPB4609F',
  pekrn: '',
  email: '',
  fromDate: '01-Jan-1950',
  toDate: '26-Oct-2024 ',
  data: [
    {
      dtTransaction: [
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'D',
          amcName: 'DSP Mutual Fund',
          folio: '8805642',
          checkDigit: '54',
          trxnDate: '26-DEC-2023',
          postedDate: '26-DEC-2023',
          scheme: '905',
          schemeName:
            'DSP Nifty Smallcap250 Quality 50 Index Fund - Direct - Growth ',
          trxnDesc: 'NFO Purchase-BSE - - INZ000208032',
          trxnAmount: '100.00',
          trxnUnits: '10.000',
          purchasePrice: '10.0000',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.00',
          trxnCharge: '0.00',
          trxnTypeFlag: 'NFOFP',
          isin: 'INF740KA1TW1',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'D',
          amcName: 'DSP Mutual Fund',
          folio: '8805642',
          checkDigit: '54',
          trxnDate: '26-DEC-2023',
          postedDate: '26-DEC-2023',
          scheme: '905',
          schemeName:
            'DSP Nifty Smallcap250 Quality 50 Index Fund - Direct - Growth ',
          trxnDesc:
            'Registration of NomineeNominee addition through - MFC-276907520-360583536',
          trxnAmount: '0',
          trxnUnits: '0',
          purchasePrice: '0',
          sttTax: '0',
          tax: '0',
          totalTax: '0',
          trxnMode: 'N',
          stampDuty: '0',
          trxnCharge: '0',
          trxnTypeFlag: '',
          isin: 'INF740KA1TW1',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'D',
          amcName: 'DSP Mutual Fund',
          folio: '8805642',
          checkDigit: '54',
          trxnDate: '27-DEC-2023',
          postedDate: '27-DEC-2023',
          scheme: '905',
          schemeName:
            'DSP Nifty Smallcap250 Quality 50 Index Fund - Direct - Growth ',
          trxnDesc: 'Address Updated from KRA Data - First Holder',
          trxnAmount: '0',
          trxnUnits: '0',
          purchasePrice: '0',
          sttTax: '0',
          tax: '0',
          totalTax: '0',
          trxnMode: 'N',
          stampDuty: '0',
          trxnCharge: '0',
          trxnTypeFlag: '',
          isin: 'INF740KA1TW1',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'PP',
          amcName: 'PPFAS Mutual Fund',
          folio: '14168669',
          checkDigit: '',
          trxnDate: '18-DEC-2023',
          postedDate: '18-DEC-2023',
          scheme: '001ZG',
          schemeName:
            'Parag Parikh Flexi Cap Fund - Direct Plan (formerly Parag Parikh Long Term Value Fund)',
          trxnDesc: 'Purchase Systematic-BSE - Instalment No - 1',
          trxnAmount: '3999.80',
          trxnUnits: '57.457',
          purchasePrice: '69.6142',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.20',
          trxnCharge: '0.00',
          trxnTypeFlag: 'FPS',
          isin: 'INF879O01027',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'PP',
          amcName: 'PPFAS Mutual Fund',
          folio: '14168669',
          checkDigit: '',
          trxnDate: '19-DEC-2023',
          postedDate: '19-DEC-2023',
          scheme: '001ZG',
          schemeName:
            'Parag Parikh Flexi Cap Fund - Direct Plan (formerly Parag Parikh Long Term Value Fund)',
          trxnDesc: 'Address Updated from KRA Data',
          trxnAmount: '0',
          trxnUnits: '0',
          purchasePrice: '0',
          sttTax: '0',
          tax: '0',
          totalTax: '0',
          trxnMode: 'N',
          stampDuty: '0',
          trxnCharge: '0',
          trxnTypeFlag: '',
          isin: 'INF879O01027',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'PP',
          amcName: 'PPFAS Mutual Fund',
          folio: '14168669',
          checkDigit: '',
          trxnDate: '20-DEC-2023',
          postedDate: '20-DEC-2023',
          scheme: '001ZG',
          schemeName:
            'Parag Parikh Flexi Cap Fund - Direct Plan (formerly Parag Parikh Long Term Value Fund)',
          trxnDesc:
            'Registration of NomineeNominee addition through - MFC-269592780-130056252',
          trxnAmount: '0',
          trxnUnits: '0',
          purchasePrice: '0',
          sttTax: '0',
          tax: '0',
          totalTax: '0',
          trxnMode: 'N',
          stampDuty: '0',
          trxnCharge: '0',
          trxnTypeFlag: '',
          isin: 'INF879O01027',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'PP',
          amcName: 'PPFAS Mutual Fund',
          folio: '14168669',
          checkDigit: '',
          trxnDate: '16-FEB-2024',
          postedDate: '16-FEB-2024',
          scheme: '001ZG',
          schemeName:
            'Parag Parikh Flexi Cap Fund - Direct Plan (formerly Parag Parikh Long Term Value Fund)',
          trxnDesc: 'Purchase Systematic-BSE - Instalment No - 2/1000',
          trxnAmount: '3999.80',
          trxnUnits: '53.473',
          purchasePrice: '74.8005',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.20',
          trxnCharge: '0.00',
          trxnTypeFlag: 'APS',
          isin: 'INF879O01027',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'PP',
          amcName: 'PPFAS Mutual Fund',
          folio: '14168669',
          checkDigit: '',
          trxnDate: '19-MAR-2024',
          postedDate: '19-MAR-2024',
          scheme: '001ZG',
          schemeName:
            'Parag Parikh Flexi Cap Fund - Direct Plan (formerly Parag Parikh Long Term Value Fund)',
          trxnDesc: 'Purchase Systematic-BSE - Instalment No - 3/1000',
          trxnAmount: '3999.80',
          trxnUnits: '54.454',
          purchasePrice: '73.4526',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.20',
          trxnCharge: '0.00',
          trxnTypeFlag: 'APS',
          isin: 'INF879O01027',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'PP',
          amcName: 'PPFAS Mutual Fund',
          folio: '14168669',
          checkDigit: '',
          trxnDate: '16-APR-2024',
          postedDate: '16-APR-2024',
          scheme: '001ZG',
          schemeName:
            'Parag Parikh Flexi Cap Fund - Direct Plan (formerly Parag Parikh Long Term Value Fund)',
          trxnDesc: 'Purchase Systematic-BSE - Instalment No - 4/1000',
          trxnAmount: '3999.80',
          trxnUnits: '52.774',
          purchasePrice: '75.7907',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.20',
          trxnCharge: '0.00',
          trxnTypeFlag: 'APS',
          isin: 'INF879O01027',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'PP',
          amcName: 'PPFAS Mutual Fund',
          folio: '14168669',
          checkDigit: '',
          trxnDate: '16-MAY-2024',
          postedDate: '16-MAY-2024',
          scheme: '001ZG',
          schemeName:
            'Parag Parikh Flexi Cap Fund - Direct Plan (formerly Parag Parikh Long Term Value Fund)',
          trxnDesc: 'Purchase Systematic-BSE - Instalment No - 5/1000',
          trxnAmount: '3999.80',
          trxnUnits: '51.393',
          purchasePrice: '77.8270',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.20',
          trxnCharge: '0.00',
          trxnTypeFlag: 'APS',
          isin: 'INF879O01027',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'PP',
          amcName: 'PPFAS Mutual Fund',
          folio: '14168669',
          checkDigit: '',
          trxnDate: '18-JUN-2024',
          postedDate: '18-JUN-2024',
          scheme: '001ZG',
          schemeName:
            'Parag Parikh Flexi Cap Fund - Direct Plan (formerly Parag Parikh Long Term Value Fund)',
          trxnDesc: 'Purchase Systematic-BSE - Instalment No - 6/1000',
          trxnAmount: '3999.80',
          trxnUnits: '49.403',
          purchasePrice: '80.9622',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.20',
          trxnCharge: '0.00',
          trxnTypeFlag: 'APS',
          isin: 'INF879O01027',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'PP',
          amcName: 'PPFAS Mutual Fund',
          folio: '14168669',
          checkDigit: '',
          trxnDate: '16-JUL-2024',
          postedDate: '16-JUL-2024',
          scheme: '001ZG',
          schemeName:
            'Parag Parikh Flexi Cap Fund - Direct Plan (formerly Parag Parikh Long Term Value Fund)',
          trxnDesc: 'Purchase Systematic-BSE - Instalment No - 7/1000',
          trxnAmount: '3999.80',
          trxnUnits: '47.444',
          purchasePrice: '84.3059',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.20',
          trxnCharge: '0.00',
          trxnTypeFlag: 'APS',
          isin: 'INF879O01027',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'PP',
          amcName: 'PPFAS Mutual Fund',
          folio: '14168669',
          checkDigit: '',
          trxnDate: '18-JUL-2024',
          postedDate: '18-JUL-2024',
          scheme: '001ZG',
          schemeName:
            'Parag Parikh Flexi Cap Fund - Direct Plan (formerly Parag Parikh Long Term Value Fund)',
          trxnDesc: 'Cancelled',
          trxnAmount: '0',
          trxnUnits: '0',
          purchasePrice: '0',
          sttTax: '0',
          tax: '0',
          totalTax: '0',
          trxnMode: 'N',
          stampDuty: '0',
          trxnCharge: '0',
          trxnTypeFlag: '',
          isin: 'INF879O01027',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'PP',
          amcName: 'PPFAS Mutual Fund',
          folio: '14168669',
          checkDigit: '',
          trxnDate: '16-AUG-2024',
          postedDate: '16-AUG-2024',
          scheme: '001ZG',
          schemeName:
            'Parag Parikh Flexi Cap Fund - Direct Plan (formerly Parag Parikh Long Term Value Fund)',
          trxnDesc: 'Purchase Systematic-BSE - Instalment No - 1',
          trxnAmount: '7999.60',
          trxnUnits: '94.804',
          purchasePrice: '84.3808',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.40',
          trxnCharge: '0.00',
          trxnTypeFlag: 'APS',
          isin: 'INF879O01027',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'PP',
          amcName: 'PPFAS Mutual Fund',
          folio: '14168669',
          checkDigit: '',
          trxnDate: '17-SEP-2024',
          postedDate: '17-SEP-2024',
          scheme: '001ZG',
          schemeName:
            'Parag Parikh Flexi Cap Fund - Direct Plan (formerly Parag Parikh Long Term Value Fund)',
          trxnDesc: 'Purchase Systematic-BSE - Instalment No - 2/999',
          trxnAmount: '7999.60',
          trxnUnits: '91.863',
          purchasePrice: '87.0823',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.40',
          trxnCharge: '0.00',
          trxnTypeFlag: 'APS',
          isin: 'INF879O01027',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'PP',
          amcName: 'PPFAS Mutual Fund',
          folio: '14168669',
          checkDigit: '',
          trxnDate: '17-OCT-2024',
          postedDate: '17-OCT-2024',
          scheme: '001ZG',
          schemeName:
            'Parag Parikh Flexi Cap Fund - Direct Plan (formerly Parag Parikh Long Term Value Fund)',
          trxnDesc: 'Purchase Systematic-BSE - Instalment No - 3/999',
          trxnAmount: '7999.60',
          trxnUnits: '91.695',
          purchasePrice: '87.2415',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.40',
          trxnCharge: '0.00',
          trxnTypeFlag: 'APS',
          isin: 'INF879O01027',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'Z',
          amcName: 'Zerodha Fund House',
          folio: '1108389553',
          checkDigit: '',
          trxnDate: '27-DEC-2023',
          postedDate: '27-DEC-2023',
          scheme: 'ZN250',
          schemeName:
            'Zerodha Nifty Large Midcap 250 Index Fund-Direct Plan - Growth ',
          trxnDesc: 'Purchase-BSE -',
          trxnAmount: '499.98',
          trxnUnits: '44.812',
          purchasePrice: '11.1572',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.02',
          trxnCharge: '0.00',
          trxnTypeFlag: 'FP',
          isin: 'INF0R8F01018',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'Z',
          amcName: 'Zerodha Fund House',
          folio: '1108389553',
          checkDigit: '',
          trxnDate: '27-DEC-2023',
          postedDate: '27-DEC-2023',
          scheme: 'ZN250',
          schemeName:
            'Zerodha Nifty Large Midcap 250 Index Fund-Direct Plan - Growth ',
          trxnDesc: 'Registration of Nominee',
          trxnAmount: '0',
          trxnUnits: '0',
          purchasePrice: '0',
          sttTax: '0',
          tax: '0',
          totalTax: '0',
          trxnMode: 'N',
          stampDuty: '0',
          trxnCharge: '0',
          trxnTypeFlag: '',
          isin: 'INF0R8F01018',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'Z',
          amcName: 'Zerodha Fund House',
          folio: '1108389553',
          checkDigit: '',
          trxnDate: '28-DEC-2023',
          postedDate: '28-DEC-2023',
          scheme: 'ZN250',
          schemeName:
            'Zerodha Nifty Large Midcap 250 Index Fund-Direct Plan - Growth ',
          trxnDesc: 'Address Updated from KRA Data',
          trxnAmount: '0',
          trxnUnits: '0',
          purchasePrice: '0',
          sttTax: '0',
          tax: '0',
          totalTax: '0',
          trxnMode: 'N',
          stampDuty: '0',
          trxnCharge: '0',
          trxnTypeFlag: '',
          isin: 'INF0R8F01018',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: '127',
          amcName: 'MOTILAL OSWAL MUTUAL FUND',
          folio: '91047338711',
          checkDigit: '0',
          trxnDate: '05-FEB-2024',
          postedDate: '05-FEB-2024',
          scheme: 'FMGDG',
          schemeName: 'Motilal Oswal Midcap Fund - Direct Plan Growth',
          trxnDesc: 'Systematic Investment (1)',
          trxnAmount: '1999.90',
          trxnUnits: '23.910',
          purchasePrice: '83.6445',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.10',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF247L01445',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: '127',
          amcName: 'MOTILAL OSWAL MUTUAL FUND',
          folio: '91047338711',
          checkDigit: '0',
          trxnDate: '19-MAR-2024',
          postedDate: '19-MAR-2024',
          scheme: 'FMGDG',
          schemeName: 'Motilal Oswal Midcap Fund - Direct Plan Growth',
          trxnDesc: 'Systematic Investment (1)',
          trxnAmount: '1999.90',
          trxnUnits: '23.709',
          purchasePrice: '84.3507',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.10',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF247L01445',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: '127',
          amcName: 'MOTILAL OSWAL MUTUAL FUND',
          folio: '91047338711',
          checkDigit: '0',
          trxnDate: '16-APR-2024',
          postedDate: '16-APR-2024',
          scheme: 'FMGDG',
          schemeName: 'Motilal Oswal Midcap Fund - Direct Plan Growth',
          trxnDesc: 'Systematic Investment (1)',
          trxnAmount: '1999.90',
          trxnUnits: '22.103',
          purchasePrice: '90.4811',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.10',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF247L01445',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: '127',
          amcName: 'MOTILAL OSWAL MUTUAL FUND',
          folio: '91047338711',
          checkDigit: '0',
          trxnDate: '16-MAY-2024',
          postedDate: '16-MAY-2024',
          scheme: 'FMGDG',
          schemeName: 'Motilal Oswal Midcap Fund - Direct Plan Growth',
          trxnDesc: 'Systematic Investment (1)',
          trxnAmount: '1999.90',
          trxnUnits: '21.184',
          purchasePrice: '94.4063',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.10',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF247L01445',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: '127',
          amcName: 'MOTILAL OSWAL MUTUAL FUND',
          folio: '91047338711',
          checkDigit: '0',
          trxnDate: '18-JUN-2024',
          postedDate: '18-JUN-2024',
          scheme: 'FMGDG',
          schemeName: 'Motilal Oswal Midcap Fund - Direct Plan Growth',
          trxnDesc: 'Systematic Investment (1)',
          trxnAmount: '1999.90',
          trxnUnits: '18.988',
          purchasePrice: '105.3224',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.10',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF247L01445',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: '127',
          amcName: 'MOTILAL OSWAL MUTUAL FUND',
          folio: '91047338711',
          checkDigit: '0',
          trxnDate: '18-JUN-2024',
          postedDate: '18-JUN-2024',
          scheme: 'FMGDG',
          schemeName: 'Motilal Oswal Midcap Fund - Direct Plan Growth',
          trxnDesc: 'Purchase',
          trxnAmount: '1999.90',
          trxnUnits: '18.988',
          purchasePrice: '105.3224',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.10',
          trxnCharge: '0.00',
          trxnTypeFlag: 'ADD',
          isin: 'INF247L01445',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: '127',
          amcName: 'MOTILAL OSWAL MUTUAL FUND',
          folio: '91047338711',
          checkDigit: '0',
          trxnDate: '16-JUL-2024',
          postedDate: '16-JUL-2024',
          scheme: 'FMGDG',
          schemeName: 'Motilal Oswal Midcap Fund - Direct Plan Growth',
          trxnDesc: 'Systematic Investment (1)',
          trxnAmount: '1999.90',
          trxnUnits: '17.958',
          purchasePrice: '111.3654',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.10',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF247L01445',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: '127',
          amcName: 'MOTILAL OSWAL MUTUAL FUND',
          folio: '91047338711',
          checkDigit: '0',
          trxnDate: '16-AUG-2024',
          postedDate: '16-AUG-2024',
          scheme: 'FMGDG',
          schemeName: 'Motilal Oswal Midcap Fund - Direct Plan Growth',
          trxnDesc: 'Systematic Investment (1)',
          trxnAmount: '5999.70',
          trxnUnits: '53.115',
          purchasePrice: '112.9577',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.30',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF247L01445',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: '127',
          amcName: 'MOTILAL OSWAL MUTUAL FUND',
          folio: '91047338711',
          checkDigit: '0',
          trxnDate: '17-SEP-2024',
          postedDate: '17-SEP-2024',
          scheme: 'FMGDG',
          schemeName: 'Motilal Oswal Midcap Fund - Direct Plan Growth',
          trxnDesc: 'Systematic Investment (1)',
          trxnAmount: '5999.70',
          trxnUnits: '49.576',
          purchasePrice: '121.0211',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.30',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF247L01445',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: '127',
          amcName: 'MOTILAL OSWAL MUTUAL FUND',
          folio: '91047338711',
          checkDigit: '0',
          trxnDate: '17-OCT-2024',
          postedDate: '17-OCT-2024',
          scheme: 'FMGDG',
          schemeName: 'Motilal Oswal Midcap Fund - Direct Plan Growth',
          trxnDesc: 'Systematic Investment (1)',
          trxnAmount: '5999.70',
          trxnUnits: '48.914',
          purchasePrice: '122.6573',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.30',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF247L01445',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'RMF',
          amcName: 'Nippon India Mutual Fund',
          folio: '477308761191',
          checkDigit: '0',
          trxnDate: '18-DEC-2023',
          postedDate: '18-DEC-2023',
          scheme: 'SCAGG',
          schemeName:
            'NIPPON INDIA SMALL CAP FUND - DIRECT GROWTH PLAN GROWTH OPTION',
          trxnDesc: 'Sys. Investment (1/1)',
          trxnAmount: '499.98',
          trxnUnits: '3.300',
          purchasePrice: '151.5320',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.02',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF204K01K15',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'RMF',
          amcName: 'Nippon India Mutual Fund',
          folio: '477308761191',
          checkDigit: '0',
          trxnDate: '16-FEB-2024',
          postedDate: '16-FEB-2024',
          scheme: 'SCAGG',
          schemeName:
            'NIPPON INDIA SMALL CAP FUND - DIRECT GROWTH PLAN GROWTH OPTION',
          trxnDesc: 'Sys. Investment (1/1)',
          trxnAmount: '499.98',
          trxnUnits: '3.152',
          purchasePrice: '158.6344',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.02',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF204K01K15',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'RMF',
          amcName: 'Nippon India Mutual Fund',
          folio: '477308761191',
          checkDigit: '0',
          trxnDate: '19-MAR-2024',
          postedDate: '19-MAR-2024',
          scheme: 'SCAGG',
          schemeName:
            'NIPPON INDIA SMALL CAP FUND - DIRECT GROWTH PLAN GROWTH OPTION',
          trxnDesc: 'Sys. Investment (1/1)',
          trxnAmount: '499.98',
          trxnUnits: '3.336',
          purchasePrice: '149.8615',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.02',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF204K01K15',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'RMF',
          amcName: 'Nippon India Mutual Fund',
          folio: '477308761191',
          checkDigit: '0',
          trxnDate: '16-APR-2024',
          postedDate: '16-APR-2024',
          scheme: 'SCAGG',
          schemeName:
            'NIPPON INDIA SMALL CAP FUND - DIRECT GROWTH PLAN GROWTH OPTION',
          trxnDesc: 'Sys. Investment (1/1)',
          trxnAmount: '499.98',
          trxnUnits: '3.084',
          purchasePrice: '162.1146',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.02',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF204K01K15',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'RMF',
          amcName: 'Nippon India Mutual Fund',
          folio: '477308761191',
          checkDigit: '0',
          trxnDate: '16-MAY-2024',
          postedDate: '16-MAY-2024',
          scheme: 'SCAGG',
          schemeName:
            'NIPPON INDIA SMALL CAP FUND - DIRECT GROWTH PLAN GROWTH OPTION',
          trxnDesc: 'Sys. Investment (1/1)',
          trxnAmount: '499.98',
          trxnUnits: '2.885',
          purchasePrice: '173.2875',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.02',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF204K01K15',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'RMF',
          amcName: 'Nippon India Mutual Fund',
          folio: '477308761191',
          checkDigit: '0',
          trxnDate: '18-JUN-2024',
          postedDate: '18-JUN-2024',
          scheme: 'SCAGG',
          schemeName:
            'NIPPON INDIA SMALL CAP FUND - DIRECT GROWTH PLAN GROWTH OPTION',
          trxnDesc: 'Sys. Investment (1/1)',
          trxnAmount: '499.98',
          trxnUnits: '2.652',
          purchasePrice: '188.5231',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.02',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF204K01K15',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'RMF',
          amcName: 'Nippon India Mutual Fund',
          folio: '477308761191',
          checkDigit: '0',
          trxnDate: '16-JUL-2024',
          postedDate: '16-JUL-2024',
          scheme: 'SCAGG',
          schemeName:
            'NIPPON INDIA SMALL CAP FUND - DIRECT GROWTH PLAN GROWTH OPTION',
          trxnDesc: 'Sys. Investment (1/1)',
          trxnAmount: '499.98',
          trxnUnits: '2.549',
          purchasePrice: '196.1623',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.02',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF204K01K15',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'RMF',
          amcName: 'Nippon India Mutual Fund',
          folio: '477308761191',
          checkDigit: '0',
          trxnDate: '16-AUG-2024',
          postedDate: '16-AUG-2024',
          scheme: 'SCAGG',
          schemeName:
            'NIPPON INDIA SMALL CAP FUND - DIRECT GROWTH PLAN GROWTH OPTION',
          trxnDesc: 'Sys. Investment (1/1)',
          trxnAmount: '1999.90',
          trxnUnits: '10.329',
          purchasePrice: '193.6156',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.10',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF204K01K15',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'RMF',
          amcName: 'Nippon India Mutual Fund',
          folio: '477308761191',
          checkDigit: '0',
          trxnDate: '17-SEP-2024',
          postedDate: '17-SEP-2024',
          scheme: 'SCAGG',
          schemeName:
            'NIPPON INDIA SMALL CAP FUND - DIRECT GROWTH PLAN GROWTH OPTION',
          trxnDesc: 'Sys. Investment (1/1)',
          trxnAmount: '1999.90',
          trxnUnits: '9.856',
          purchasePrice: '202.9164',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.10',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF204K01K15',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'RMF',
          amcName: 'Nippon India Mutual Fund',
          folio: '477308761191',
          checkDigit: '0',
          trxnDate: '17-OCT-2024',
          postedDate: '17-OCT-2024',
          scheme: 'SCAGG',
          schemeName:
            'NIPPON INDIA SMALL CAP FUND - DIRECT GROWTH PLAN GROWTH OPTION',
          trxnDesc: 'Sys. Investment (1/1)',
          trxnAmount: '1999.90',
          trxnUnits: '9.925',
          purchasePrice: '201.4949',
          sttTax: '0.00',
          tax: '0.00',
          totalTax: '0.00',
          trxnMode: 'N',
          stampDuty: '0.10',
          trxnCharge: '0.00',
          trxnTypeFlag: 'SIN',
          isin: 'INF204K01K15',
        },
      ],
      dtSummary: [
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'D',
          amcName: 'DSP Mutual Fund',
          folio: '8805642',
          scheme: '905',
          schemeName:
            'DSP Nifty Smallcap250 Quality 50 Index Fund - Direct - Growth ',
          kycStatus: '3',
          brokerCode: 'INZ000208032',
          brokerName: 'NEXTBILLION TECHNOLOGY PRIVATE LIMITED',
          rtaCode: 'CAMS',
          decimalUnits: '3',
          decimalAmount: '2',
          decimalNav: '4',
          lastTrxnDate: '26-DEC-2023',
          openingBal: '0.000',
          marketValue: '123.23',
          nav: '12.3231',
          closingBalance: '10.000',
          lastNavDate: '25-OCT-2024',
          isDemat: 'N',
          assetType: 'EQUITY',
          isin: 'INF740KA1TW1',
          nomineeStatus: 'Y',
          taxStatus: '01',
          costValue: '100',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'PP',
          amcName: 'PPFAS Mutual Fund',
          folio: '14168669',
          scheme: '001ZG',
          schemeName:
            'Parag Parikh Flexi Cap Fund - Direct Plan (formerly Parag Parikh Long Term Value Fund)',
          kycStatus: '3',
          brokerCode: 'INZ000208032',
          brokerName: 'Nextbillion Technology Private Ltd',
          rtaCode: 'CAMS',
          decimalUnits: '3',
          decimalAmount: '2',
          decimalNav: '4',
          lastTrxnDate: '17-OCT-2024',
          openingBal: '0.000',
          marketValue: '55747.11',
          nav: '86.4618',
          closingBalance: '644.760',
          lastNavDate: '24-OCT-2024',
          isDemat: 'N',
          assetType: 'EQUITY',
          isin: 'INF879O01027',
          nomineeStatus: 'Y',
          taxStatus: '01',
          costValue: '52000',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'Z',
          amcName: 'Zerodha Fund House',
          folio: '1108389553',
          scheme: 'ZN250',
          schemeName:
            'Zerodha Nifty Large Midcap 250 Index Fund-Direct Plan - Growth ',
          kycStatus: '3',
          brokerCode: 'INZ000208032',
          brokerName: 'INZ000208032',
          rtaCode: 'CAMS',
          decimalUnits: '3',
          decimalAmount: '2',
          decimalNav: '4',
          lastTrxnDate: '27-DEC-2023',
          openingBal: '0.000',
          marketValue: '594.99',
          nav: '13.2775',
          closingBalance: '44.812',
          lastNavDate: '25-OCT-2024',
          isDemat: 'N',
          assetType: 'EQUITY',
          isin: 'INF0R8F01018',
          nomineeStatus: 'Y',
          taxStatus: '01',
          costValue: '500',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: '127',
          amcName: 'MOTILAL OSWAL MUTUAL FUND',
          folio: '91047338711',
          scheme: 'FMGDG',
          schemeName: 'Motilal Oswal Midcap Fund - Direct Plan Growth',
          kycStatus: '3',
          brokerCode: 'INZ000208032',
          brokerName: 'DIRECT',
          rtaCode: 'KFINTECH',
          decimalUnits: '3',
          decimalAmount: '2',
          decimalNav: '4',
          lastTrxnDate: '17-OCT-2024',
          openingBal: '0.000',
          marketValue: '35288.55',
          nav: '118.2414',
          closingBalance: '298.445',
          lastNavDate: '25-OCT-2024',
          isDemat: 'N',
          assetType: 'EQUITY',
          isin: 'INF247L01445',
          nomineeStatus: 'Y',
          taxStatus: 'I',
          costValue: '32000.00',
        },
        {
          email: 'vedantbhamare11@gmail.com',
          amc: 'RMF',
          amcName: 'Nippon India Mutual Fund',
          folio: '477308761191',
          scheme: 'SCAGG',
          schemeName:
            'NIPPON INDIA SMALL CAP FUND - DIRECT GROWTH PLAN GROWTH OPTION',
          kycStatus: '3',
          brokerCode: 'INZ000208032',
          brokerName: 'DIRECT',
          rtaCode: 'KFINTECH',
          decimalUnits: '3',
          decimalAmount: '2',
          decimalNav: '4',
          lastTrxnDate: '17-OCT-2024',
          openingBal: '0.000',
          marketValue: '9700.11',
          nav: '189.9450',
          closingBalance: '51.068',
          lastNavDate: '25-OCT-2024',
          isDemat: 'N',
          assetType: 'EQUITY',
          isin: 'INF204K01K15',
          nomineeStatus: 'Y',
          taxStatus: '1',
          costValue: '9500.00',
        },
      ],
    },
  ],
  investorDetails: {
    address: {
      address1: 'C O NARENDRA BHAMARE B 2002 CLAREMONT LODHA',
      address2: 'LUXURIA THANE WEST MAJIWADA THANE THANE THANE THANE',
      address3: 'MAHARASHTRA 400601',
      city: 'THANE',
      district: '',
      state: 'MAHARASHTRA',
      pincode: '400601',
      country: 'INDIA',
    },
    email: 'vedantbhamare11@gmail.com',
    mobile: '7588310400',
    investorFirstName: '  VEDANT NARENDRA BHAMARE',
    investorMiddleName: null,
    investorLastName: null,
  },
};
